package http

import (
	"context"
	"net/http"

	"github.com/go-chi/chi/v5"
	chimw "github.com/go-chi/chi/v5/middleware"

	"github.com/udaykishore-resu/cloudoptix/internal/domain/core"
	"github.com/udaykishore-resu/cloudoptix/internal/infrastructure/auth"
)

// principalCtxKey and requestIDCtxKey are unexported so nothing outside this
// package can construct a principal in a request context by hand — the
// authentication middleware is the only writer.
type authMethodCtxKey struct{}

// PrincipalFrom returns the authenticated principal attached by the
// authentication middleware. core.PrincipalFrom (which this delegates to)
// already defines the canonical storage key, shared with every application
// service — using the same accessor here means a handler and the service it
// calls always see the identical principal, with no risk of a second,
// transport-local copy drifting from it.
func PrincipalFrom(ctx context.Context) (core.Principal, bool) {
	return core.PrincipalFrom(ctx)
}

// MustPrincipal panics if no principal is attached. It exists only for
// handlers reached after the authentication middleware, where its absence is
// a wiring bug, not a request the client could ever trigger — the panic
// recovery middleware turns it into a 500 problem+json rather than crashing
// the process, and the panic message names the missing precondition instead
// of surfacing a nil-pointer stack trace to the operator debugging it.
func MustPrincipal(ctx context.Context) core.Principal {
	p, ok := PrincipalFrom(ctx)
	if !ok {
		panic("http: handler reached with no principal in context — authentication middleware is not wired ahead of it")
	}
	return p
}

// WithAuthMethod records which credential path authenticated the request
// ("oidc" | "service_token" | "dev_token" | "api_key"), which the access log
// and audit middleware both read to label the actor.
func WithAuthMethod(ctx context.Context, method string) context.Context {
	return context.WithValue(ctx, authMethodCtxKey{}, method)
}

// AuthMethodFrom returns the recorded credential path, or "" if none.
func AuthMethodFrom(ctx context.Context) string {
	m, _ := ctx.Value(authMethodCtxKey{}).(string)
	return m
}

// RequestIDFrom returns chi's per-request id, generated by the RequestID
// middleware early in the chain. It is what ties one client-visible error to
// the exact log lines and audit record a support engineer needs.
func RequestIDFrom(ctx context.Context) string {
	return chimw.GetReqID(ctx)
}

// URLParam is a thin wrapper over chi.URLParam kept here so handler files
// import this package's helpers and not chi directly — the day chi is
// swapped for something else, only this file changes.
func URLParam(r *http.Request, key string) string { return chi.URLParam(r, key) }

// PathID reads a chi URL parameter as a core.ID.
func PathID(r *http.Request, key string) core.ID { return core.ID(URLParam(r, key)) }

// clientIP resolves the caller's address for the audit log.
//
// It reads r.RemoteAddr, which realIPMiddleware has already resolved: the
// socket peer by default, or the forwarded client address when — and only
// when — the request arrived from a declared trusted proxy. See realip.go.
func clientIP(r *http.Request) string { return r.RemoteAddr }

// authResultCtxKey carries the full auth.AuthResult (principal + method),
// set once by the authentication middleware; PrincipalFrom/AuthMethodFrom
// above are the narrow accessors handlers actually use.
type authResultCtxKey struct{}

func withAuthResult(ctx context.Context, res auth.AuthResult) context.Context {
	ctx = core.WithPrincipal(ctx, res.Principal)
	ctx = WithAuthMethod(ctx, res.Method)
	return context.WithValue(ctx, authResultCtxKey{}, res)
}
