package cloud

import (
	"time"

	"github.com/udaykishore-resu/cloudoptix/internal/domain/core"
)

// AccessMode records how CloudOptix reaches a customer account. Only
// AssumeRole is supported for real accounts: CloudOptix never accepts, stores
// or transmits long-lived AWS access keys, so there is no code path that could
// leak one.
//
// Traceability: REQ-SEC-001, SPEC-SEC-001.
type AccessMode string

const (
	AccessAssumeRole AccessMode = "assume_role"
	// AccessSimulated points the adapters at the in-repo AWS simulator. It is
	// how the demo tenant and the entire test suite run without an AWS
	// account, and it is rejected for any tenant not flagged as a demo.
	AccessSimulated AccessMode = "simulated"
)

// ConnectionState is the lifecycle of an onboarded AWS account.
type ConnectionState string

const (
	ConnPending   ConnectionState = "pending"   // role details captured, not yet verified
	ConnVerifying ConnectionState = "verifying" // STS AssumeRole + permission probe running
	ConnConnected ConnectionState = "connected" // verified, discovery may run
	ConnDegraded  ConnectionState = "degraded"  // connected but missing optional permissions
	ConnFailed    ConnectionState = "failed"    // AssumeRole or probe failed
	ConnSuspended ConnectionState = "suspended" // disabled by the tenant
)

// RoleScope separates the four permission tiers CloudOptix requests. They are
// distinct IAM roles rather than one role with a wide policy, so a tenant can
// grant discovery without ever granting mutation.
type RoleScope string

const (
	ScopeRead    RoleScope = "read"    // Describe*/List*/Get* on inventory
	ScopeAnalyze RoleScope = "analyze" // CloudWatch, Cost Explorer, CUR
	ScopePlan    RoleScope = "plan"    // dry-run/simulate APIs only
	ScopeExecute RoleScope = "execute" // the narrow mutating set, per action type
)

// AWSAccount is an onboarded customer account.
type AWSAccount struct {
	ID          core.ID          `json:"id"`
	TenantID    core.TenantID    `json:"tenant_id"`
	AccountID   core.AccountID   `json:"account_id"`
	Alias       string           `json:"alias,omitempty"`
	Environment core.Environment `json:"environment"`
	Regions     []core.Region    `json:"regions"`
	AccessMode  AccessMode       `json:"access_mode"`
	// RoleARNs maps each scope to the role CloudOptix assumes. A tenant that
	// declines automation simply never creates the execute role, and the
	// execution engine's precondition check fails closed.
	RoleARNs map[RoleScope]core.ARN `json:"role_arns"`
	// ExternalID is the confused-deputy defence. It is generated by
	// CloudOptix, unique per account, and must be present in the customer's
	// trust policy.
	ExternalID string `json:"external_id"`
	// SessionName prefix used for every AssumeRole call, so the customer's
	// CloudTrail attributes every action to CloudOptix and to the CloudOptix
	// principal that requested it.
	SessionPrefix string `json:"session_prefix"`

	State           ConnectionState `json:"state"`
	StateReason     string          `json:"state_reason,omitempty"`
	GrantedScopes   []RoleScope     `json:"granted_scopes"`
	MissingActions  []string        `json:"missing_actions,omitempty"`
	IsPayer         bool            `json:"is_payer"`
	CURBucket       string          `json:"cur_bucket,omitempty"`
	CURPrefix       string          `json:"cur_prefix,omitempty"`
	ConnectedAt     time.Time       `json:"connected_at,omitempty"`
	LastVerifiedAt  time.Time       `json:"last_verified_at,omitempty"`
	LastDiscoveryAt time.Time       `json:"last_discovery_at,omitempty"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

// HasScope reports whether a permission tier was verified as granted.
func (a AWSAccount) HasScope(s RoleScope) bool {
	for _, g := range a.GrantedScopes {
		if g == s {
			return true
		}
	}
	return false
}

// CanExecute reports whether automation is even possible for this account.
// The execution engine calls this first; a tenant that never created the
// execute role can enable automation in the UI and still be safe.
func (a AWSAccount) CanExecute() bool {
	return a.State == ConnConnected && a.HasScope(ScopeExecute) && a.RoleARNs[ScopeExecute] != ""
}

// Validate enforces the account invariants at onboarding time.
func (a AWSAccount) Validate() error {
	var v core.ValidationResult
	if a.TenantID.IsZero() {
		v.Add("tenant_id", "required", core.SeverityCritical, "account must be tenant-scoped")
	}
	if err := a.AccountID.Validate(); err != nil {
		v.Add("account_id", "invalid", core.SeverityCritical, "%v", err)
	}
	if len(a.Regions) == 0 {
		v.Add("regions", "required", core.SeverityHigh, "at least one region must be selected")
	}
	switch a.AccessMode {
	case AccessAssumeRole:
		if a.RoleARNs[ScopeRead] == "" {
			v.Add("role_arns.read", "required", core.SeverityCritical,
				"a read role ARN is required; CloudOptix never accepts access keys")
		}
		if a.ExternalID == "" {
			v.Add("external_id", "required", core.SeverityCritical,
				"an external ID is required to prevent the confused-deputy attack")
		}
	case AccessSimulated:
		// permitted only for demo tenants; enforced in the application layer
	default:
		v.Add("access_mode", "invalid", core.SeverityCritical,
			"access mode %q is not supported", a.AccessMode)
	}
	return v.Err()
}

// Application is a business-facing unit of software, the level at which
// executives ask "what does this cost".
type Application struct {
	ID           core.ID            `json:"id"`
	TenantID     core.TenantID      `json:"tenant_id"`
	Name         string             `json:"name"`
	Slug         string             `json:"slug"`
	Description  string             `json:"description,omitempty"`
	BusinessUnit string             `json:"business_unit,omitempty"`
	Domain       string             `json:"domain,omitempty"` // ecommerce, claims, payments
	Criticality  core.Criticality   `json:"criticality"`
	Owner        string             `json:"owner,omitempty"`
	Environments []core.Environment `json:"environments"`
	// MatchRules attribute resources to this application. Attribution is
	// declarative and auditable rather than an opaque heuristic, because a
	// misattributed resource silently corrupts every economics figure
	// downstream.
	MatchRules []AttributionRule `json:"match_rules,omitempty"`
	CreatedAt  time.Time         `json:"created_at"`
	UpdatedAt  time.Time         `json:"updated_at"`
}

// Workload is a deployable unit inside an application: a microservice, a job,
// a queue consumer. It is the finest granularity at which CloudOptix reports
// economic footprint.
type Workload struct {
	ID            core.ID          `json:"id"`
	TenantID      core.TenantID    `json:"tenant_id"`
	ApplicationID core.ID          `json:"application_id"`
	Name          string           `json:"name"`
	Type          WorkloadType     `json:"type"`
	Platform      Platform         `json:"platform"`
	Environment   core.Environment `json:"environment"`
	Criticality   core.Criticality `json:"criticality"`
	Owner         string           `json:"owner,omitempty"`
	Team          string           `json:"team,omitempty"`
	// Namespace/Cluster locate a Kubernetes workload; empty otherwise.
	Cluster    string            `json:"cluster,omitempty"`
	Namespace  string            `json:"namespace,omitempty"`
	MatchRules []AttributionRule `json:"match_rules,omitempty"`
	SLO        WorkloadSLO       `json:"slo"`
	CreatedAt  time.Time         `json:"created_at"`
	UpdatedAt  time.Time         `json:"updated_at"`
}

// WorkloadType classifies the runtime shape, which drives which optimization
// rules are even applicable.
type WorkloadType string

const (
	WorkloadMicroservice WorkloadType = "microservice"
	WorkloadAPI          WorkloadType = "api"
	WorkloadBatch        WorkloadType = "batch"
	WorkloadStream       WorkloadType = "stream"
	WorkloadWorker       WorkloadType = "worker"
	WorkloadDatastore    WorkloadType = "datastore"
	WorkloadFrontend     WorkloadType = "frontend"
	WorkloadMLTraining   WorkloadType = "ml_training"
	WorkloadMLInference  WorkloadType = "ml_inference"
)

// Platform is the compute substrate.
type Platform string

const (
	PlatformEKS        Platform = "eks"
	PlatformECS        Platform = "ecs"
	PlatformFargate    Platform = "fargate"
	PlatformEC2        Platform = "ec2"
	PlatformLambda     Platform = "lambda"
	PlatformManagedSvc Platform = "managed_service"
	PlatformUnknown    Platform = "unknown"
)

// WorkloadSLO is the reliability and performance contract that the validation
// engine checks a change against. An optimization that saves money but breaks
// one of these is a failed optimization, and CloudOptix rolls it back.
type WorkloadSLO struct {
	AvailabilityTarget float64         `json:"availability_target,omitempty"` // 0.9999
	LatencyP95MS       float64         `json:"latency_p95_ms,omitempty"`
	LatencyP99MS       float64         `json:"latency_p99_ms,omitempty"`
	ErrorRateMax       float64         `json:"error_rate_max,omitempty"` // 0.001
	ThroughputMinRPS   float64         `json:"throughput_min_rps,omitempty"`
	Source             core.Provenance `json:"source"`
}

// IsSet reports whether any target was defined.
func (s WorkloadSLO) IsSet() bool {
	return s.AvailabilityTarget > 0 || s.LatencyP95MS > 0 || s.LatencyP99MS > 0 ||
		s.ErrorRateMax > 0 || s.ThroughputMinRPS > 0
}

// AttributionRule maps resources to an application or workload. Rules are
// evaluated in priority order and the first match wins, so the result is
// deterministic and explainable: the UI can always say which rule claimed a
// resource.
type AttributionRule struct {
	Priority   int            `json:"priority"`
	TagKey     string         `json:"tag_key,omitempty"`
	TagValue   string         `json:"tag_value,omitempty"`
	NamePrefix string         `json:"name_prefix,omitempty"`
	AccountID  core.AccountID `json:"account_id,omitempty"`
	Region     core.Region    `json:"region,omitempty"`
	Kinds      []Kind         `json:"kinds,omitempty"`
	Namespace  string         `json:"namespace,omitempty"`
	Cluster    string         `json:"cluster,omitempty"`
	Note       string         `json:"note,omitempty"`
}

// Matches evaluates the rule against a resource. Every populated field must
// match; empty fields are wildcards.
func (r AttributionRule) Matches(res Resource) bool {
	if r.TagKey != "" {
		v, ok := res.Tags.Get(r.TagKey)
		if !ok {
			return false
		}
		if r.TagValue != "" && core.Normalize(v) != core.Normalize(r.TagValue) {
			return false
		}
	}
	if r.NamePrefix != "" && !hasPrefixFold(res.DisplayName(), r.NamePrefix) {
		return false
	}
	if r.AccountID != "" && res.AccountID != r.AccountID {
		return false
	}
	if r.Region != "" && res.Region != r.Region {
		return false
	}
	if r.Namespace != "" && res.Attr("namespace", "") != r.Namespace {
		return false
	}
	if r.Cluster != "" && res.Attr("cluster", "") != r.Cluster {
		return false
	}
	if len(r.Kinds) > 0 {
		found := false
		for _, k := range r.Kinds {
			if res.Kind == k {
				found = true
				break
			}
		}
		if !found {
			return false
		}
	}
	// A rule with no populated field would match everything, which is never
	// the intent and would swallow the whole estate into one application.
	return r.TagKey != "" || r.NamePrefix != "" || r.AccountID != "" ||
		r.Region != "" || r.Namespace != "" || r.Cluster != "" || len(r.Kinds) > 0
}

func hasPrefixFold(s, prefix string) bool {
	if len(prefix) > len(s) {
		return false
	}
	return core.Normalize(s[:len(prefix)]) == core.Normalize(prefix)
}
