// Package iampolicy builds the least-privilege AWS IAM artefacts CloudOptix
// asks a customer to create: the trust policy that enforces the
// confused-deputy external-id defence, and one policy document per
// permission tier (read, analyze, plan, execute).
//
// KEY DESIGN DECISION: this logic used to live twice — once inside
// internal/application/onboarding (which needs it to build the "next steps"
// shown right after a specification is approved) and, before this package
// existed, it would have needed a second private copy inside
// internal/application/awsaccounts (which needs the identical policy
// documents when an AWS account is actually registered and whenever a
// customer asks to regenerate onboarding instructions). Two copies of a
// security-critical action list is exactly the kind of duplication that
// drifts silently: a new discoverer's IAM action gets added to one copy and
// not the other, and the gap is invisible until a customer's role denies a
// call CloudOptix believed it had granted. Factoring it here means both
// callers — and any future one — read the exact same action lists and the
// exact same trust-policy shape.
//
// Every action list here is additive-only within its tier and
// resource-unrestricted ("Resource": "*"): CloudOptix does not know a
// customer's resource ARNs until discovery, running under this very role,
// finds them. What keeps the grant narrow is the fixed, reviewable action
// list, not a resource constraint.
//
// Traceability: REQ-SEC-001, SPEC-SEC-001.
package iampolicy

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/udaykishore-resu/cloudoptix/internal/domain/cloud"
	"github.com/udaykishore-resu/cloudoptix/internal/domain/optimize"
	"github.com/udaykishore-resu/cloudoptix/internal/ports"
)

// PlatformAccountEnv names the CloudOptix platform AWS account whose
// principal a customer's role trust policy must name. It is read from the
// environment rather than hard-coded so a self-hosted or per-region
// deployment can point customers at the right account without a code
// change; a clearly-marked placeholder is used when unset (development and
// the test suite), and the instructions text says so explicitly rather than
// silently handing out a fake-looking but plausible ARN.
const PlatformAccountEnv = "CLOUDOPTIX_PLATFORM_ACCOUNT_ID"

// PlatformPrincipalARN returns the ARN a customer's trust policy must name
// as the allowed AssumeRole principal.
func PlatformPrincipalARN() string {
	acct := strings.TrimSpace(os.Getenv(PlatformAccountEnv))
	if acct == "" {
		acct = "000000000000" // placeholder; see PlatformAccountEnv doc comment
	}
	return fmt.Sprintf("arn:aws:iam::%s:root", acct)
}

// GenerateExternalID mints the confused-deputy external ID a customer's
// trust policy must require CloudOptix to present on every AssumeRole call.
// It is opaque, per-account, and generated by CloudOptix rather than chosen
// by the customer — the property that makes it useful as a defence at all.
func GenerateExternalID() string {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		// crypto/rand failing is unrecoverable in the same way core.NewID
		// treats it: an external id that is not actually random is worse
		// than no external id.
		panic(fmt.Sprintf("iampolicy: entropy source failed: %v", err))
	}
	return "cloudoptix-" + hex.EncodeToString(b[:])
}

// scopeReadActions / scopeAnalyzeActions / scopePlanActions are the fixed,
// read-only AWS API surface each tier needs. They are wide within their tier
// (Describe*/List*/Get* covers whatever inventory or metrics discovery adds
// next) but the tier itself is what a customer is actually deciding to
// grant: read alone, or read plus cost/metrics analysis, or read plus
// dry-run simulation — never anything that can change a resource.
var scopeReadActions = []string{
	"ec2:Describe*", "rds:Describe*", "rds:ListTagsForResource",
	"s3:ListAllMyBuckets", "s3:GetBucketLocation", "s3:GetBucketTagging", "s3:GetBucketLifecycleConfiguration",
	"lambda:List*", "lambda:GetFunction*",
	"ecs:Describe*", "ecs:List*",
	"eks:Describe*", "eks:List*",
	"elasticloadbalancing:Describe*",
	"autoscaling:Describe*",
	"dynamodb:Describe*", "dynamodb:List*",
	"elasticache:Describe*",
	"tag:GetResources", "tag:GetTagKeys", "tag:GetTagValues",
	"organizations:ListAccounts", "organizations:DescribeOrganization",
}

var scopeAnalyzeActions = []string{
	"ce:GetCostAndUsage", "ce:GetCostForecast", "ce:GetReservationUtilization",
	"ce:GetSavingsPlansUtilization", "ce:GetRightsizingRecommendation",
	"cur:DescribeReportDefinitions",
	"cloudwatch:GetMetricData", "cloudwatch:GetMetricStatistics", "cloudwatch:ListMetrics",
	"pricing:GetProducts", "pricing:DescribeServices",
	"compute-optimizer:Get*",
}

var scopePlanActions = []string{
	// Every action here is a read-only or dry-run capability: EC2 and RDS
	// both honour DryRun on the mutating call itself, which is what
	// CloudOptix's plan/simulate stage actually calls — never the mutating
	// call with DryRun omitted.
	"ec2:DescribeInstanceAttribute",
	"pricing:GetProducts",
	"compute-optimizer:GetEC2InstanceRecommendations",
	"compute-optimizer:GetRDSDatabaseRecommendations",
}

// executeActionsByType maps each optimize.ActionType to the narrow IAM
// action list its executor needs, so the execute-tier policy grants exactly
// the mutating APIs CloudOptix's own executors call — nothing broader. A
// destructive action type (optimize.ActionType.Destructive) is still
// included here: the platform's own policy engine refuses to
// auto-execute it (see internal/domain/govern.Policy.Validate), but a human
// approving a specific deletion still needs the IAM permission to carry it
// out once approved.
var executeActionsByType = map[optimize.ActionType][]string{
	optimize.ActionResizeInstance:               {"ec2:ModifyInstanceAttribute", "ec2:StopInstances", "ec2:StartInstances"},
	optimize.ActionStopInstance:                 {"ec2:StopInstances"},
	optimize.ActionTerminateInstance:            {"ec2:TerminateInstances"},
	optimize.ActionDeleteVolume:                 {"ec2:DeleteVolume"},
	optimize.ActionResizeVolume:                 {"ec2:ModifyVolume"},
	optimize.ActionModifyVolumeType:             {"ec2:ModifyVolume"},
	optimize.ActionDeleteSnapshot:               {"ec2:DeleteSnapshot"},
	optimize.ActionDeregisterAMI:                {"ec2:DeregisterImage", "ec2:DeleteSnapshot"},
	optimize.ActionReleaseElasticIP:             {"ec2:ReleaseAddress"},
	optimize.ActionResizeRDS:                    {"rds:ModifyDBInstance"},
	optimize.ActionModifyRDSStorage:             {"rds:ModifyDBInstance"},
	optimize.ActionRemoveRDSReplica:             {"rds:DeleteDBInstance"},
	optimize.ActionStopRDS:                      {"rds:StopDBInstance"},
	optimize.ActionApplyS3Lifecycle:             {"s3:PutBucketLifecycleConfiguration"},
	optimize.ActionAbortMultipartUploads:        {"s3:AbortMultipartUpload", "s3:ListMultipartUploadParts", "s3:ListBucketMultipartUploads"},
	optimize.ActionSetLogRetention:              {"logs:PutRetentionPolicy"},
	optimize.ActionResizeLambdaMemory:           {"lambda:UpdateFunctionConfiguration"},
	optimize.ActionRemoveProvisionedConcurrency: {"lambda:DeleteProvisionedConcurrencyConfig"},
	optimize.ActionSwitchLambdaArch:             {"lambda:UpdateFunctionConfiguration"},
	optimize.ActionResizeNodeGroup:              {"eks:UpdateNodegroupConfig", "autoscaling:UpdateAutoScalingGroup"},
	optimize.ActionAdjustPodResources:           {"eks:DescribeCluster"}, // applied via the cluster's own API, not the AWS control plane
	optimize.ActionEnableSpot:                   {"autoscaling:UpdateAutoScalingGroup", "ec2:CreateFleet"},
	optimize.ActionCreateVPCEndpoint:            {"ec2:CreateVpcEndpoint"},
	optimize.ActionRemoveNATGateway:             {"ec2:DeleteNatGateway"},
	optimize.ActionScheduleShutdown:             {"ec2:StopInstances", "ec2:StartInstances", "rds:StopDBInstance", "rds:StartDBInstance"},
	optimize.ActionPurchaseCommitment:           {"ce:GetSavingsPlansPurchaseRecommendation", "savingsplans:CreateSavingsPlan"},
	optimize.ActionSwitchDynamoBilling:          {"dynamodb:UpdateTable"},
}

// BuildPolicyDocument renders an AWS IAM policy document (JSON, as a Go
// map ready for json.Marshal) that grants exactly the actions a RoleScope
// needs, resource-unrestricted but action-restricted to the fixed lists
// above.
func BuildPolicyDocument(scope cloud.RoleScope) map[string]any {
	var actions []string
	switch scope {
	case cloud.ScopeRead:
		actions = scopeReadActions
	case cloud.ScopeAnalyze:
		actions = append(append([]string{}, scopeReadActions...), scopeAnalyzeActions...)
	case cloud.ScopePlan:
		actions = append(append([]string{}, scopeReadActions...), scopePlanActions...)
	case cloud.ScopeExecute:
		seen := map[string]bool{}
		for _, list := range executeActionsByType {
			for _, a := range list {
				seen[a] = true
			}
		}
		for a := range seen {
			actions = append(actions, a)
		}
	}
	return map[string]any{
		"Version": "2012-10-17",
		"Statement": []map[string]any{
			{
				"Sid":      "CloudOptix" + titleCase(string(scope)),
				"Effect":   "Allow",
				"Action":   actions,
				"Resource": "*",
			},
		},
	}
}

// RoleName builds the per-tenant, per-scope IAM role name a customer creates
// in their own account. Keeping the tenant slug in the name is what lets a
// customer with several CloudOptix relationships (an MSP scenario) tell
// roles apart in their own IAM console.
func RoleName(tenantSlug string, scope cloud.RoleScope) string {
	return fmt.Sprintf("CloudOptix-%s-%s", tenantSlug, titleCase(string(scope)))
}

// titleCase upper-cases just the first byte of s. strings.Title is
// deprecated (it does not handle full Unicode casing); every string this
// package feeds it is one of the fixed, ASCII cloud.RoleScope values, so
// that generality was never needed.
func titleCase(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// TrustPolicyDocument is the trust policy the customer attaches to each
// role, requiring both the CloudOptix platform principal and the per-account
// external id — the confused-deputy defence.
func TrustPolicyDocument(externalID string) map[string]any {
	return map[string]any{
		"Version": "2012-10-17",
		"Statement": []map[string]any{
			{
				"Effect":    "Allow",
				"Principal": map[string]any{"AWS": PlatformPrincipalARN()},
				"Action":    "sts:AssumeRole",
				"Condition": map[string]any{
					"StringEquals": map[string]any{"sts:ExternalId": externalID},
				},
			},
		},
	}
}

// BuildInstructions assembles the full ports.AWSOnboardingInstructions
// packet for one tenant: which roles to create, the least-privilege policy
// to attach to each, and the shared trust policy that binds them to
// externalID. includeExecute adds the mutating tier's role and policy —
// callers pass it as the tenant's current automation.enabled setting, since
// there is no reason to ask a customer to create a role CloudOptix will
// never assume.
//
// externalID is a caller-provided value rather than one this function mints
// itself: a fresh account being registered wants a newly generated id (see
// GenerateExternalID), but instructions regenerated for an already-connected
// account must reuse its existing external id — the customer's trust policy
// already requires it, and handing back a different one here would make the
// regenerated instructions describe a role that can no longer assume.
func BuildInstructions(tenantSlug, externalID string, includeExecute bool) ports.AWSOnboardingInstructions {
	scopes := []cloud.RoleScope{cloud.ScopeRead, cloud.ScopeAnalyze, cloud.ScopePlan}
	if includeExecute {
		scopes = append(scopes, cloud.ScopeExecute)
	}

	roleNames := make(map[cloud.RoleScope]string, len(scopes))
	policyDocs := make(map[cloud.RoleScope]string, len(scopes))
	for _, sc := range scopes {
		roleNames[sc] = RoleName(tenantSlug, sc)
		if b, err := json.MarshalIndent(BuildPolicyDocument(sc), "", "  "); err == nil {
			policyDocs[sc] = string(b)
		}
	}
	trustJSON := ""
	if b, err := json.MarshalIndent(TrustPolicyDocument(externalID), "", "  "); err == nil {
		trustJSON = string(b)
	}

	instructions := []string{
		fmt.Sprintf("In each AWS account CloudOptix should analyse, create one IAM role per permission tier below (%d total), using this trust policy — every role must require external id %q:\n%s",
			len(scopes), externalID, trustJSON),
		"Attach the matching least-privilege policy document to each role (see policy_documents, one per tier).",
		"Provide the resulting role ARNs back to CloudOptix to complete account verification.",
		"CloudOptix never requests or stores long-lived AWS access keys, and the execute-tier role is only requested when automation is enabled in the specification.",
	}

	return ports.AWSOnboardingInstructions{
		ExternalID: externalID, TrustedPrincipalARN: PlatformPrincipalARN(),
		RoleNames: roleNames, PolicyDocuments: policyDocs, Instructions: instructions,
	}
}
