{{- if .Values.serviceMonitor.enabled }}
{{- range $name, $comp := .Values.components }}
{{- if $comp.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cloudoptix.componentFullname" (list $ $name $comp) }}
  namespace: {{ $.Values.serviceMonitor.namespace | default $.Release.Namespace }}
  labels:
    {{- include "cloudoptix.componentLabels" (list $ $name $comp) | nindent 4 }}
    {{- with $.Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "cloudoptix.componentSelectorLabels" (list $ $name $comp) | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ $.Values.serviceMonitor.interval }}
---
{{- end }}
{{- end }}
{{- end }}
