// Package simulate models the three forward-looking engines: architecture
// mutation (what else could this be), counterfactuals (what if the world
// changed), and the cost compiler (what will this change cost before it
// ships).
//
// All three share one discipline: a simulated number is never presented as a
// measurement. Every result carries its assumptions, the confidence in each,
// and the pricing basis used — because the failure mode of architecture
// simulation is a confident chart built on a silently wrong assumption about
// request rate or data transfer.
//
// Traceability: REQ-SIM-001..010, REQ-CC-001..008, SPEC-SIM-001.
package simulate

import (
	"sort"
	"time"

	"github.com/udaykishore-resu/cloudoptix/internal/domain/core"
)

// Assumption is an input the simulation could not measure and had to assume.
// The UI renders these prominently and lets the user override each one, which
// is what turns a simulation from a claim into a model.
type Assumption struct {
	Key         string          `json:"key"`
	Label       string          `json:"label"`
	Value       string          `json:"value"`
	Unit        string          `json:"unit,omitempty"`
	Provenance  core.Provenance `json:"provenance"`
	Sensitivity float64         `json:"sensitivity,omitempty"` // d(result)/d(assumption), normalized
	Note        string          `json:"note,omitempty"`
}

// Dimension is one axis on which architecture candidates are scored. Cost is
// deliberately not the only one: an architecture that is 40% cheaper and one
// SPOF worse is not an improvement, and a tool that only ranks by cost will
// keep recommending it.
type Dimension string

const (
	DimCost            Dimension = "cost"
	DimPerformance     Dimension = "performance"
	DimReliability     Dimension = "reliability"
	DimScalability     Dimension = "scalability"
	DimSecurity        Dimension = "security"
	DimOperability     Dimension = "operational_complexity"
	DimMigrationEffort Dimension = "migration_complexity"
	DimRisk            Dimension = "risk"
)

// DimensionScore is a 0..100 rating on one axis with its reasoning.
type DimensionScore struct {
	Dimension  Dimension       `json:"dimension"`
	Score      float64         `json:"score"`
	Delta      float64         `json:"delta"` // versus the current architecture
	Rationale  string          `json:"rationale"`
	Confidence core.Confidence `json:"confidence"`
}

// ComponentChange describes one difference between architectures.
type ComponentChange struct {
	Action       string     `json:"action"` // "replace" | "add" | "remove" | "resize" | "keep"
	From         string     `json:"from,omitempty"`
	To           string     `json:"to,omitempty"`
	Component    string     `json:"component"`
	MonthlyDelta core.Money `json:"monthly_delta"`
	Rationale    string     `json:"rationale"`
	Effort       string     `json:"effort,omitempty"`
}

// Candidate is one alternative architecture generated by the mutation engine.
type Candidate struct {
	ID           core.ID       `json:"id"`
	TenantID     core.TenantID `json:"tenant_id"`
	SimulationID core.ID       `json:"simulation_id"`
	Name         string        `json:"name"`
	Summary      string        `json:"summary"`
	Pattern      string        `json:"pattern"` // "serverless" | "containerized" | "managed_data" | ...

	Changes []ComponentChange `json:"changes"`

	CurrentMonthlyCost   core.Money `json:"current_monthly_cost"`
	ProjectedMonthlyCost core.Money `json:"projected_monthly_cost"`
	MonthlyDelta         core.Money `json:"monthly_delta"`
	AnnualDelta          core.Money `json:"annual_delta"`
	SavingsPct           float64    `json:"savings_pct"`

	Scores      []DimensionScore `json:"scores"`
	Composite   float64          `json:"composite_score"`
	Assumptions []Assumption     `json:"assumptions"`
	Risks       []string         `json:"risks,omitempty"`
	Blockers    []string         `json:"blockers,omitempty"`
	// MigrationSteps is the outline plan. It is advisory: the mutation engine
	// proposes architectures, it does not execute migrations.
	MigrationSteps []string        `json:"migration_steps,omitempty"`
	Confidence     core.Confidence `json:"confidence"`
	Recommended    bool            `json:"recommended"`
}

// Score returns the value on a dimension, or the neutral 50 when unscored.
func (c Candidate) Score(d Dimension) float64 {
	for _, s := range c.Scores {
		if s.Dimension == d {
			return s.Score
		}
	}
	return 50
}

// Weights control how dimension scores combine into the composite. A tenant's
// risk tolerance from the onboarding spec maps directly onto these.
type Weights map[Dimension]float64

// DefaultWeights is the balanced stance used when a tenant expresses no
// preference.
func DefaultWeights() Weights {
	return Weights{
		DimCost: 0.30, DimReliability: 0.20, DimPerformance: 0.15,
		DimOperability: 0.12, DimScalability: 0.10, DimSecurity: 0.08,
		DimMigrationEffort: 0.05,
	}
}

// WeightsForRiskTolerance adjusts the stance. A low-risk-tolerance tenant
// weights reliability and migration effort far higher, which usually demotes
// the aggressive serverless rewrite that a pure cost ranking would put first.
func WeightsForRiskTolerance(tolerance string) Weights {
	w := DefaultWeights()
	switch core.Normalize(tolerance) {
	case "low", "conservative":
		w[DimCost] = 0.18
		w[DimReliability] = 0.30
		w[DimMigrationEffort] = 0.15
		w[DimOperability] = 0.15
		w[DimPerformance] = 0.12
		w[DimScalability] = 0.05
		w[DimSecurity] = 0.05
	case "high", "aggressive":
		w[DimCost] = 0.45
		w[DimReliability] = 0.15
		w[DimMigrationEffort] = 0.02
		w[DimOperability] = 0.08
		w[DimPerformance] = 0.15
		w[DimScalability] = 0.10
		w[DimSecurity] = 0.05
	}
	return w
}

// Composite computes the weighted score for a candidate.
func (w Weights) Composite(c Candidate) float64 {
	var sum, total float64
	for dim, weight := range w {
		sum += c.Score(dim) * weight
		total += weight
	}
	if total == 0 {
		return 0
	}
	return sum / total
}

// Simulation is a run of the mutation engine over a scope.
type Simulation struct {
	ID       core.ID       `json:"id"`
	TenantID core.TenantID `json:"tenant_id"`
	Name     string        `json:"name"`
	Scope    string        `json:"scope"` // "application" | "workload" | "account"
	ScopeID  core.ID       `json:"scope_id"`
	Kind     Kind          `json:"kind"`

	BaselineCost core.Money   `json:"baseline_cost"`
	Candidates   []Candidate  `json:"candidates"`
	Weights      Weights      `json:"weights"`
	Assumptions  []Assumption `json:"assumptions"`

	RequestedBy string    `json:"requested_by"`
	CreatedAt   time.Time `json:"created_at"`
	CompletedAt time.Time `json:"completed_at,omitempty"`
	Status      string    `json:"status"`
	Error       string    `json:"error,omitempty"`
}

// Kind distinguishes the simulation types.
type Kind string

const (
	KindArchitectureMutation Kind = "architecture_mutation"
	KindCounterfactual       Kind = "counterfactual"
	KindCostCompiler         Kind = "cost_compiler"
)

// RankCandidates scores and orders candidates, flagging the recommended one.
func RankCandidates(cands []Candidate, w Weights) []Candidate {
	for i := range cands {
		cands[i].Composite = w.Composite(cands[i])
		cands[i].Recommended = false
	}
	sort.SliceStable(cands, func(i, j int) bool { return cands[i].Composite > cands[j].Composite })
	if len(cands) > 0 {
		cands[0].Recommended = true
	}
	return cands
}

// ScenarioType enumerates the counterfactual questions CloudOptix answers.
type ScenarioType string

const (
	ScenarioTrafficChange      ScenarioType = "traffic_change"
	ScenarioPlatformChange     ScenarioType = "platform_change"
	ScenarioDatabaseChange     ScenarioType = "database_change"
	ScenarioAddCache           ScenarioType = "add_cache"
	ScenarioRemoveNAT          ScenarioType = "remove_nat"
	ScenarioAddVPCEndpoint     ScenarioType = "add_vpc_endpoint"
	ScenarioSpotAdoption       ScenarioType = "spot_adoption"
	ScenarioRegionChange       ScenarioType = "region_change"
	ScenarioCommitmentPurchase ScenarioType = "commitment_purchase"
	ScenarioStorageClass       ScenarioType = "storage_class_change"
	ScenarioReplicaChange      ScenarioType = "replica_change"
	ScenarioCustom             ScenarioType = "custom"
)

// Scenario is a counterfactual question with its parameters.
type Scenario struct {
	Type       ScenarioType   `json:"type"`
	Label      string         `json:"label"`
	Parameters map[string]any `json:"parameters"`
	ScopeID    core.ID        `json:"scope_id,omitempty"`
}

// Counterfactual is the answer to a what-if.
type Counterfactual struct {
	ID       core.ID       `json:"id"`
	TenantID core.TenantID `json:"tenant_id"`
	Scenario Scenario      `json:"scenario"`
	Question string        `json:"question"`

	CurrentState  StateProjection `json:"current_state"`
	ProposedState StateProjection `json:"proposed_state"`

	CostDelta        core.Money `json:"cost_delta"`
	CostDeltaPct     float64    `json:"cost_delta_pct"`
	AnnualCostDelta  core.Money `json:"annual_cost_delta"`
	PerformanceDelta string     `json:"performance_delta"`
	ReliabilityDelta string     `json:"reliability_delta"`
	SecurityDelta    string     `json:"security_delta,omitempty"`

	Risk        core.RiskLevel  `json:"risk"`
	Confidence  core.Confidence `json:"confidence"`
	Assumptions []Assumption    `json:"assumptions"`
	Caveats     []string        `json:"caveats,omitempty"`
	Narrative   string          `json:"narrative,omitempty"`
	ComputedAt  time.Time       `json:"computed_at"`
}

// StateProjection is the modelled state of an architecture under a scenario.
type StateProjection struct {
	Label        string                `json:"label"`
	MonthlyCost  core.Money            `json:"monthly_cost"`
	ByService    map[string]core.Money `json:"by_service,omitempty"`
	Components   []ProjectedComponent  `json:"components,omitempty"`
	P95LatencyMS float64               `json:"p95_latency_ms,omitempty"`
	Availability float64               `json:"availability,omitempty"`
	Notes        []string              `json:"notes,omitempty"`
}

// ProjectedComponent is one modelled component under a scenario.
type ProjectedComponent struct {
	Name        string     `json:"name"`
	Kind        string     `json:"kind"`
	Quantity    float64    `json:"quantity"`
	Unit        string     `json:"unit"`
	MonthlyCost core.Money `json:"monthly_cost"`
}
